env = Environment()

debug = ARGUMENTS.get('DEBUG', '1')
cflags = ARGUMENTS.get('CFLAGS', '')

if debug == '1':
    cflags += '-g'

sources = ['list.c', 'color.c']
libmix = env.SharedLibrary(target = 'mix', source = sources,
                           CFLAGS = cflags)
