Import('env', 'debug', 'cflags', 'destdir')

sources = ['list.c', 'color.c', 'util.c',
           'group.c', 'extension.c', 'mixer.c',
           'libmix.c']

libmix = env.SharedLibrary(target = 'mix', source = sources,
                           CFLAGS = cflags)

env.Install(destdir, libmix)
env.Alias('install', destdir)
